name: Continuous Integration (CI)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  wrapper-validation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  build-tests:
    name: Build Tests
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle modules
        uses: actions/cache@v2
        timeout-minutes: 5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/dependencies.kt') }}

      - name: Build, lint, and run unit tests
        run: ./gradlew assemble bundle lint test --scan

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --scan

      - name: Generate test coverage report
        run: ./gradlew jacocoTestReport --scan

      - name: Check code style
        run: ./gradlew spotlessCheck --scan

      - name: Upload build output files
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build report files
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: app/build/reports
