name: Continuous Integration (CI)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug variant.
        run: ./gradlew assembleDebug bundleDebug testDebug --scan

      - name: Build release variant.
        run: ./gradlew assembleRelease bundleRelease testRelease --scan

      - name: Check code style and lint.
        run: ./gradlew spotlessCheck lint --scan

      - name: Upload build output files.
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build report files.
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: app/build/reports

      - name: Check dependency updates.
        run: ./gradlew dependencyUpdates --scan

      - name: Upload dependency updates report.
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates
