name: Continuous Integration (CI)
on: [push]
jobs:
  validate:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Cache gradle modules
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test debug variant
        run: ./gradlew assembleDebug bundleDebug testDebug --scan

      - name: Build and test release variant
        run: ./gradlew assembleRelease bundleRelease testRelease --scan

      - name: Run instrumented tests
        if: runner.os == 'macOS'
        uses: reactivecircus/android-emulator-runner@v2.5.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Check code style and lint
        run: ./gradlew spotlessCheck lint --scan

      - name: Upload build output files
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs-${{ runner.os }}
          path: app/build/outputs

      - name: Upload build report files
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports-${{ runner.os }}
          path: app/build/reports
